name: example
description: A example application for country and currency picker package.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  currency_country_picker:
    path: ../
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fl_country_code_picker: ^0.1.9+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true