name: currency_country_picker
description: A flutter package to select country with phone code and currency.

homepage: https://github.com/Ehsan-abaci
repository: https://github.com/Ehsan-abaci/currency_country_picker

version: 1.1.1+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
